FORMAT: 1A
HOST: http://felixlapal.me/

# Oktoberfest

L'API du truc de l'évènement où le monde boivent de la bière.


## Information générale [/info]

### Get general info [GET]

+ Response 200 (application/json)
    + Attributes
        - start_time: `11-11-2016 21:00` (string)
        - sponsors (array)
          - (Sponsor)
              - id: 1
              - image_url: `https://unsplash.it/74/75?random`
          - (Sponsor)
              - id: 2
              - image_url: `https://unsplash.it/75/75?random`
          - (Sponsor)
              - id: 3
              - image_url: `https://unsplash.it/75/74?random`
          - (Sponsor)
              - id: 4
              - image_url: `https://unsplash.it/76/75?random`  
          - (Sponsor)
              - id: 5
              - image_url: `https://unsplash.it/75/76?random`
          - (Sponsor)
              - id: 6
              - image_url: `https://unsplash.it/74/76?random`

## Programmation [/schedule_items]

### Get All Schedule Items [GET]

+ Response 200 (application/json)
    + Attributes (array)
        - (Schedule Item)
            - id: 1
            - large_image_url: `http://lorempixel.com/400/200/`
        - (Schedule Item)
            - id: 2
            - large_image_url: `http://lorempixel.com/400/201/`
        - (Schedule Item)
            - id: 3
            - large_image_url: `http://lorempixel.com/401/200/`

## Horaire bus [/bus_schedule]

### Get horaire bus [GET]

+ Response 200 (application/json)
    + Attributes (array)
        - (Bus Path)
            - id: 1
        - (Bus Path)
            - id: 2
        - (Bus Path)
            - id: 3
        
        
## Coordonnées [/contact]

### Get coordonnées [GET]

+ Response 200 (application/json)

        {
            "snapchat": "oktosherby",
            "twitter": "Okto_sherbrooke",
            "facebook": "Oktoberfest Sherbrooke",
            "facebook_user": "oktoberfest.sherbrooke",
            "website_url": "http://oktoberfest.ageg.ca/",
            "email": "felix@lapal.me",
            "physical_address": "Apple\n1 Infinite Loop\nCupertino, California\nUSA",
        }
        
## Bières [/bieres]

### Liste des bières [GET]

+ Response 200 (application/json)
    + Attributes (array)
        - (BeerCategory)
            - id: 1
            - name: Artisanale
            - beers (array[Beer])
                - (Beer)
                   - id: 1
                   - name: blblbll
                - (Beer)
                  - id: 2
                  - name: aha ahaha aha
                - (Beer)
                  - id: 3
                  - name: oohohohoewo
        - (BeerCategory)
            - id: 2
            - name: Non-artisanales
            - beers (array[Beer])
                - (Beer)
                   - id: 4
                   - name: blblbll
                - (Beer)
                  - id: 5
                  - name: aha ahaha aha
                - (Beer)
                  - id: 6
                  - name: oohohohoewo

## FAQ [/faq]

### Get FAQ as markdown [GET]

+ Response 200 (application/json)

        {
          "markdown": "### Quoi?\nOkay\n\n### Où?\nLà!"
        }
        
## Plan [/plan]

### Get plan [GET]

+ Response 200 (application/json)

        {
          "map_url": "http://site.com/image.jpg"
          "map_coordinates": "43.555,-43.555"
        }
    
          
# Data Structures

## Schedule Item (object)

- id: 123 (number, required)
- name: `Led Zeppelin` (string, required)
- start_time: `08-08-2016 03:00` (string, required)
- end_time: `08-08-2016 05:00` (string, required)
- large_image_url: `http://lorempixel.com/400/200/` (string, required)
- small_image_url: `http://felixlapal.me/okto/beer.png` (string, required)
- description: `une description normale là` (string)

## Bus Path (object)

- id: 12 (number, required)
- path: Coordinate (array[Coordinate])
- title: `Campus Principal` (required)
- start_time: `17:30` (required)
- interval: 30 (number, required)
- additionnal_string: `Retour seulement`
- thumbnail_url: `http://lorempixel.com/50/50/`

## Beer (object)

- id: 12 (number, required)
- name: `Molson Dry` (required)
- alcohol: 5.5 (number)
- description: `Une bière qui coute pas cher`
- image_url: `http://felixlapal.me/okto/keith.png`

## BeerCategory (object)

- id: 1 (number, required)
- name: `Artisanales` (required)
- beers: Beer (array[Beer])

## Coordinate (object)

- longitude: `43.555` (number, required)
- latitude: `-33.555` (number, required)
- annotation_image_url: `http://overlay.com/image.png` (string)

## Sponsor (object)

- id: 1 (number, required)ehold
- name: `Blabla` (required)
- image_url: `http://lorempixel.com/50/75/` (required)
- website_url: `http://apple.com/`